### ISSUE TITLE
Method for `children()`

### ISSUE THREAD

**Issue by nick-ulle** [omegahat/RClangSimple#4]
The `children()` function does not have a method for `FunctionDecl` objects, so calling `children()` on a routine accessed through `getRoutines()` does not work.

A workaround is to use `getChildren()` instead of `children()`.

As a minimal example, consider the file `example.c`:
```c
int f()
{
  return 0;
}
```

We can load this file with RCIndex to reproduce the error:
```r
library(RCIndex)

tu = createTU("example.c")
r = getRoutines(tu)

children(r$f)
# Error in visitChildren(top, f, clone = TRUE) :
#  no slot of name "ref" for this object of class "FunctionDecl"
```
This bug affects the current commit of RCIndex.

**Comment by duncantl** [comment]
Thanks. Pushed a fix to dereference the native element.
